# Generated by Django 4.2.24 on 2025-09-30 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBooking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('day_booking_date_of_purchase', models.DateField(auto_now_add=True)),
                ('day_booking_date', models.DateField()),
                ('day_booking_adults', models.IntegerField(default=0)),
                ('day_booking_children', models.IntegerField(default=0)),
                ('day_booking_oap', models.IntegerField(default=0)),
                ('day_total_cost', models.FloatField(default=0)),
                ('day_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='zoouser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoouser',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zoouser',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
