# Generated by Django 4.2.24 on 2025-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_daybooking_zoouser_date_of_birth_zoouser_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_name', models.CharField(max_length=200)),
                ('billing_address', models.CharField(max_length=200)),
                ('billing_postcode', models.CharField(max_length=6)),
                ('billing_city', models.CharField(max_length=200)),
                ('card_num', models.CharField(max_length=16)),
                ('card_expiry', models.DateField()),
                ('card_cvv', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
    ]
