# Generated by Django 4.2.24 on 2025-10-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_checkout_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='website.ticket'),
        ),
    ]
